//
//  UntilOffStyleKit.h
//  UntilOff
//
//  Created by Dominik Hauser on 18.10.14.
//  Copyright (c) 2014 Dominik Hauser. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface UntilOffStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* settingsIconTargets;

// Generated Images
+ (UIImage*)imageOfSettingsIconWithSize: (CGSize)size;

@end
